services:
  db:
    image: postgres:latest
    container_name: manga_vault_db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: manga_vault_db

# docker-compose up - command